/**
 * Schemable instances for Arbitrary
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 2.0.0
 */
import * as Arb from 'schemata-ts/Arbitrary'
import { interpret } from 'schemata-ts/Schema'
import { Schemable } from 'schemata-ts/Schemable'
import * as WithAnnotate from 'schemata-ts/schemables/WithAnnotate/instances/arbitrary'
import * as WithCheckDigit from 'schemata-ts/schemables/WithCheckDigit/instances/arbitrary'
import * as WithDate from 'schemata-ts/schemables/WithDate/instances/arbitrary'
import * as WithFloat from 'schemata-ts/schemables/WithFloat/instances/arbitrary'
import * as WithInt from 'schemata-ts/schemables/WithInt/instances/arbitrary'
import * as WithInvariant from 'schemata-ts/schemables/WithInvariant/instances/arbitrary'
import * as WithJson from 'schemata-ts/schemables/WithJson/instances/arbitrary'
import * as WithMap from 'schemata-ts/schemables/WithMap/instances/arbitrary'
import * as WithOption from 'schemata-ts/schemables/WithOption/instances/arbitrary'
import * as WithOptional from 'schemata-ts/schemables/WithOptional/instances/arbitrary'
import * as WithPadding from 'schemata-ts/schemables/WithPadding/instances/arbitrary'
import * as WithPattern from 'schemata-ts/schemables/WithPattern/instances/arbitrary'
import * as WithRefine from 'schemata-ts/schemables/WithRefine/instances/arbitrary'
import * as WithStructM from 'schemata-ts/schemables/WithStructM/instances/arbitrary'
import * as WithUnknown from 'schemata-ts/schemables/WithUnknown/instances/arbitrary'

/**
 * @since 2.0.0
 * @category Instances
 */
const ArbitrarySchemable: Schemable<Arb.SchemableLambda> = {
  ...WithAnnotate.Arbitrary,
  ...WithCheckDigit.Arbitrary,
  ...WithDate.Arbitrary,
  ...WithFloat.Arbitrary,
  ...WithInt.Arbitrary,
  ...WithInvariant.Arbitrary,
  ...WithJson.Arbitrary,
  ...WithMap.Arbitrary,
  ...WithOption.Arbitrary,
  ...WithOptional.Arbitrary,
  ...WithPadding.Arbitrary,
  ...WithPattern.Arbitrary,
  ...WithRefine.Arbitrary,
  ...WithStructM.Arbitrary,
  ...WithUnknown.Arbitrary,
}

/**
 * @since 2.0.0
 * @category Interpreters
 */
export const getArbitrary = interpret(ArbitrarySchemable)
