/**
 * Schemable instances for Arbitrary
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 2.0.0
 */
import * as Arb from 'schemata-ts/internal/arbitrary'
import { interpret } from 'schemata-ts/Schema'
import { Schemable } from 'schemata-ts/Schemable'
import * as annotate from 'schemata-ts/schemables/annotate/instances/arbitrary'
import * as array from 'schemata-ts/schemables/array/instances/arbitrary'
import * as checkDigit from 'schemata-ts/schemables/check-digit/instances/arbitrary'
import * as date from 'schemata-ts/schemables/date/instances/arbitrary'
import * as guardedUnion from 'schemata-ts/schemables/guarded-union/instances/arbitrary'
import * as invariant from 'schemata-ts/schemables/invariant/instances/arbitrary'
import * as map from 'schemata-ts/schemables/map/instances/arbitrary'
import * as option from 'schemata-ts/schemables/option/instances/arbitrary'
import * as optional from 'schemata-ts/schemables/optional/instances/arbitrary'
import * as padding from 'schemata-ts/schemables/padding/instances/arbitrary'
import * as pattern from 'schemata-ts/schemables/pattern/instances/arbitrary'
import * as primitives from 'schemata-ts/schemables/primitives/instances/arbitrary'
import * as refine from 'schemata-ts/schemables/refine/instances/arbitrary'
import * as structM from 'schemata-ts/schemables/struct/instances/arbitrary'

/**
 * @since 2.0.0
 * @category Instances
 */
const ArbitrarySchemable: Schemable<Arb.SchemableLambda> = {
  ...annotate.AnnotateArbitrary,
  ...array.ArrayArbitrary,
  ...checkDigit.CheckDigitArbitrary,
  ...date.DateArbitrary,
  ...guardedUnion.GuardedUnionArbitrary,
  ...invariant.InvariantArbitrary,
  ...map.MapArbitrary,
  ...option.OptionArbitrary,
  ...optional.OptionalArbitrary,
  ...padding.PaddingArbitrary,
  ...pattern.PatternArbitrary,
  ...primitives.PrimitivesArbitrary,
  ...refine.RefineArbitrary,
  ...structM.StructMArbitrary,
}

/**
 * @since 2.0.0
 * @category Interpreters
 */
export const getArbitrary = interpret(ArbitrarySchemable)
