/**
 * Schemable instances for Information
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 2.0.0
 */
import * as Inf from 'schemata-ts/internal/information'
import { interpret } from 'schemata-ts/Schema'
import { Schemable } from 'schemata-ts/Schemable'
import * as annotate from 'schemata-ts/schemables/annotate/instances/information'
import * as array from 'schemata-ts/schemables/array/instances/information'
import * as checkDigit from 'schemata-ts/schemables/check-digit/instances/information'
import * as clone from 'schemata-ts/schemables/clone/instances/information'
import * as date from 'schemata-ts/schemables/date/instances/information'
import * as guardedUnion from 'schemata-ts/schemables/guarded-union/instances/information'
import * as invariant from 'schemata-ts/schemables/invariant/instances/information'
import * as map from 'schemata-ts/schemables/map/instances/information'
import * as optional from 'schemata-ts/schemables/optional/instances/information'
import * as padding from 'schemata-ts/schemables/padding/instances/information'
import * as parser from 'schemata-ts/schemables/parser/instances/information'
import * as pattern from 'schemata-ts/schemables/pattern/instances/information'
import * as primitives from 'schemata-ts/schemables/primitives/instances/information'
import * as refine from 'schemata-ts/schemables/refine/instances/information'
import * as struct from 'schemata-ts/schemables/struct/instances/information'

/**
 * @since 2.0.0
 * @category Instances
 */
const InformationSchemable: Schemable<Inf.SchemableLambda> = {
  ...annotate.AnnotateInformation,
  ...array.ArrayInformation,
  ...checkDigit.CheckDigitInformation,
  ...clone.CloneInformation,
  ...date.DateInformation,
  ...guardedUnion.GuardedUnionInformation,
  ...invariant.InvariantInformation,
  ...map.MapInformation,
  ...optional.OptionalInformation,
  ...padding.PaddingInformation,
  ...parser.ParserInformation,
  ...pattern.PatternInformation,
  ...primitives.PrimitivesInformation,
  ...refine.RefineInformation,
  ...struct.StructInformation,
}

/**
 * @since 2.0.0
 * @category Interpreters
 */
export const getInformation = interpret(InformationSchemable)
