/**
 * Schemable instances for MergeSemigroup
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 2.0.0
 */
import type * as MSg from 'schemata-ts/internal/merge-semigroup'
import { interpret } from 'schemata-ts/Schema'
import { type Schemable } from 'schemata-ts/Schemable'
import * as annotate from 'schemata-ts/schemables/annotate/instances/merge-semigroup'
import * as array from 'schemata-ts/schemables/array/instances/merge-semigroup'
import * as checkDigit from 'schemata-ts/schemables/check-digit/instances/merge-semigroup'
import * as clone from 'schemata-ts/schemables/clone/instances/merge-semigroup'
import * as date from 'schemata-ts/schemables/date/instances/merge-semigroup'
import * as guardedUnion from 'schemata-ts/schemables/guarded-union/instances/merge-semigroup'
import * as invariant from 'schemata-ts/schemables/invariant/instances/merge-semigroup'
import * as lazy from 'schemata-ts/schemables/lazy/instances/merge-semigroup'
import * as map from 'schemata-ts/schemables/map/instances/merge-semigroup'
import * as optional from 'schemata-ts/schemables/optional/instances/merge-semigroup'
import * as parser from 'schemata-ts/schemables/parser/instances/merge-semigroup'
import * as pattern from 'schemata-ts/schemables/pattern/instances/merge-semigroup'
import * as primitives from 'schemata-ts/schemables/primitives/instances/merge-semigroup'
import * as refine from 'schemata-ts/schemables/refine/instances/merge-semigroup'
import * as struct from 'schemata-ts/schemables/struct/instances/merge-semigroup'

/**
 * @since 2.0.0
 * @category Instances
 */
const MergeSemigroupSchemable: Schemable<MSg.SchemableLambda> = {
  ...annotate.AnnotateMergeSemigroup,
  ...array.ArrayMergeSemigroup,
  ...checkDigit.CheckDigitMergeSemigroup,
  ...clone.CloneMergeSemigroup,
  ...date.DateMergeSemigroup,
  ...guardedUnion.GuardedUnionMergeSemigroup,
  ...invariant.InvariantMergeSemigroup,
  ...lazy.LazyMergeSemigroup,
  ...map.MapMergeSemigroup,
  ...optional.OptionalMergeSemigroup,
  ...parser.ParserMergeSemigroup,
  ...pattern.PatternMergeSemigroup,
  ...primitives.PrimitivesMergeSemigroup,
  ...refine.RefineMergeSemigroup,
  ...struct.StructMergeSemigroup,
}

/**
 * @since 2.0.0
 * @category Interpreters
 */
export const getMergeSemigroup = interpret(MergeSemigroupSchemable)
