/**
 * Schemable instances for Printer
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 2.0.0
 */
import * as P from 'schemata-ts/Printer'
import { interpret } from 'schemata-ts/Schema'
import { Schemable } from 'schemata-ts/Schemable'
import * as WithAnnotate from 'schemata-ts/schemables/WithAnnotate/instances/printer'
import * as WithCheckDigit from 'schemata-ts/schemables/WithCheckDigit/instances/printer'
import * as WithDate from 'schemata-ts/schemables/WithDate/instances/printer'
import * as WithFloat from 'schemata-ts/schemables/WithFloat/instances/printer'
import * as WithInt from 'schemata-ts/schemables/WithInt/instances/printer'
import * as WithInvariant from 'schemata-ts/schemables/WithInvariant/instances/printer'
import * as WithJson from 'schemata-ts/schemables/WithJson/instances/printer'
import * as WithMap from 'schemata-ts/schemables/WithMap/instances/printer'
import * as WithOption from 'schemata-ts/schemables/WithOption/instances/printer'
import * as WithOptional from 'schemata-ts/schemables/WithOptional/instances/printer'
import * as WithPadding from 'schemata-ts/schemables/WithPadding/instances/printer'
import * as WithPattern from 'schemata-ts/schemables/WithPattern/instances/printer'
import * as WithRefine from 'schemata-ts/schemables/WithRefine/instances/printer'
import * as WithStructM from 'schemata-ts/schemables/WithStructM/instances/printer'
import * as WithUnknown from 'schemata-ts/schemables/WithUnknown/instances/printer'

/**
 * @since 2.0.0
 * @category Instances
 */
const PrinterSchemable: Schemable<P.TypeLambda> = {
  ...P.Schemable,
  ...WithAnnotate.Printer,
  ...WithCheckDigit.Printer,
  ...WithDate.Printer,
  ...WithFloat.Printer,
  ...WithInt.Printer,
  ...WithInvariant.Printer,
  ...WithJson.Printer,
  ...WithMap.Printer,
  ...WithOption.Printer,
  ...WithOptional.Printer,
  ...WithPadding.Printer,
  ...WithPattern.Printer,
  ...WithRefine.Printer,
  ...WithStructM.Printer,
  ...WithUnknown.Printer,
}

/**
 * @since 2.0.0
 * @category Interpreters
 */
export const getPrinter = interpret(PrinterSchemable)
