/**
 * Schemable instances for Type
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @deprecated
 * @since 2.0.0
 */
import { interpret } from 'schemata-ts/Schema'
import { Schemable } from 'schemata-ts/Schemable'
import * as WithAnnotate from 'schemata-ts/schemables/WithAnnotate/instances/type'
import * as WithCheckDigit from 'schemata-ts/schemables/WithCheckDigit/instances/type'
import * as WithDate from 'schemata-ts/schemables/WithDate/instances/type'
import * as WithFloat from 'schemata-ts/schemables/WithFloat/instances/type'
import * as WithInt from 'schemata-ts/schemables/WithInt/instances/type'
import * as WithInvariant from 'schemata-ts/schemables/WithInvariant/instances/type'
import * as WithJson from 'schemata-ts/schemables/WithJson/instances/type'
import * as WithMap from 'schemata-ts/schemables/WithMap/instances/type'
import * as WithOption from 'schemata-ts/schemables/WithOption/instances/type'
import * as WithOptional from 'schemata-ts/schemables/WithOptional/instances/type'
import * as WithPadding from 'schemata-ts/schemables/WithPadding/instances/type'
import * as WithPattern from 'schemata-ts/schemables/WithPattern/instances/type'
import * as WithRefine from 'schemata-ts/schemables/WithRefine/instances/type'
import * as WithStructM from 'schemata-ts/schemables/WithStructM/instances/type'
import * as WithUnknown from 'schemata-ts/schemables/WithUnknown/instances/type'
import * as t from 'schemata-ts/Type'

/**
 * @since 2.0.0
 * @category Instances
 */
const TypeSchemable: Schemable<t.TypeLambda> = {
  ...t.Schemable,
  ...WithAnnotate.Type,
  ...WithCheckDigit.Type,
  ...WithDate.Type,
  ...WithFloat.Type,
  ...WithInt.Type,
  ...WithInvariant.Type,
  ...WithJson.Type,
  ...WithMap.Type,
  ...WithOption.Type,
  ...WithOptional.Type,
  ...WithPadding.Type,
  ...WithPattern.Type,
  ...WithRefine.Type,
  ...WithStructM.Type,
  ...WithUnknown.Type,
}

/**
 * @since 2.0.0
 * @category Interpreters
 */
export const getType = interpret(TypeSchemable)
