export const TEMP_DIR = './temp-docs'
export const SCHEMA_SRC_DIR = './src/schemata'
export const SCHEMA_OUT_DIR = './docs/schemata'

export const autogeneratedDocs: ReadonlyArray<string> = [
  'Arbitrary.ts',
  'brand.ts',
  'Eq.ts',
  'float.ts',
  'Guard.ts',
  'integer.ts',
  'JsonSchema.ts',
  'MergeSemigroup.ts',
  'newtype.ts',
  'Schema.ts',
  'TranscodeError.ts',
  'Transcoder.ts',
  'TranscoderPar.ts',
  'TypeString.ts',
]
