import { flow, pipe } from 'fp-ts/function'
import * as O from 'fp-ts/Option'
import * as RA from 'fp-ts/ReadonlyArray'
import * as RNEA from 'fp-ts/ReadonlyNonEmptyArray'
import * as Str from 'fp-ts/string'
import * as TE from 'fp-ts/TaskEither'
import * as ts from 'typescript'

import { Build } from './build'

const _ = ts.factory

export const checkTestModuleUniqueness: (test: string) => Build<ReadonlyArray<string>> =
  test => C =>
    pipe(
      TE.Do,
      TE.apS(
        'date',
        pipe(
          C.readFiles('./tests/date'),
          TE.map(RA.map(flow(Str.split('.'), RNEA.head))),
        ),
      ),
      TE.apS(
        'number',
        pipe(
          C.readFiles('./tests/number'),
          TE.map(RA.map(flow(Str.split('.'), RNEA.head))),
        ),
      ),
      TE.apS(
        'string',
        pipe(
          C.readFiles('./tests/string'),
          TE.map(RA.map(flow(Str.split('.'), RNEA.head))),
        ),
      ),
      TE.apS(
        'root',
        pipe(C.readFiles('./tests'), TE.map(RA.map(flow(Str.split('.'), RNEA.head)))),
      ),
      TE.map(({ date, number, string, root }) => [
        ...date,
        ...number,
        ...string,
        ...root,
      ]),
      TE.filterOrElse(
        flow(
          RA.findFirst(
            existingModule => Str.toLowerCase(existingModule) === Str.toLowerCase(test),
          ),
          O.isNone,
        ),
        () => new Error(`Module ${test} already exists`),
      ),
    )

const capitalize: (s: string) => string = s =>
  `${Str.toUpperCase(s.slice(0, 1))}${s.slice(1, s.length)}`

export const makeTestFile: (
  primitive: 'number' | 'string',
  moduleName_: string,
) => string = (primitive, moduleName_) => {
  const moduleName = capitalize(moduleName_)

  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed })
  const sourceFile = ts.createSourceFile(
    `${moduleName}.ts`,
    '',
    ts.ScriptTarget.Latest,
    false,
    ts.ScriptKind.TS,
  )

  return pipe(
    [
      _.createImportDeclaration(
        undefined,
        _.createImportClause(
          false,
          undefined,
          _.createNamespaceImport(_.createIdentifier('RA')),
        ),
        _.createStringLiteral('fp-ts/ReadonlyArray'),
        undefined,
      ),
      _.createImportDeclaration(
        undefined,
        _.createImportClause(
          false,
          undefined,
          _.createNamespaceImport(_.createIdentifier('E')),
        ),
        _.createStringLiteral('fp-ts/Either'),
        undefined,
      ),
      _.createImportDeclaration(
        undefined,
        _.createImportClause(
          false,
          undefined,
          _.createNamedImports([
            _.createImportSpecifier(false, undefined, _.createIdentifier('pipe')),
            _.createImportSpecifier(false, undefined, _.createIdentifier('tuple')),
          ]),
        ),
        _.createStringLiteral('fp-ts/function'),
        undefined,
      ),
      _.createImportDeclaration(
        undefined,
        _.createImportClause(
          false,
          undefined,
          _.createNamespaceImport(_.createIdentifier(moduleName)),
        ),
        _.createStringLiteral(`../../src/${primitive}/${moduleName_}`),
        undefined,
      ),
      _.createImportDeclaration(
        undefined,
        _.createImportClause(
          false,
          undefined,
          _.createNamedImports([
            _.createImportSpecifier(false, undefined, _.createIdentifier('cat')),
            _.createImportSpecifier(
              false,
              undefined,
              _.createIdentifier('combineExpected'),
            ),
            _.createImportSpecifier(
              false,
              undefined,
              _.createIdentifier('validateArbitrary'),
            ),
          ]),
        ),
        _.createStringLiteral('../../test-utils'),
        undefined,
      ),
      _.createVariableStatement(
        undefined,
        _.createVariableDeclarationList(
          [
            _.createVariableDeclaration(
              _.createIdentifier('valid'),
              undefined,
              _.createTypeReferenceNode(_.createIdentifier('ReadonlyArray'), [
                _.createKeywordTypeNode(
                  primitive === 'string'
                    ? ts.SyntaxKind.StringKeyword
                    : ts.SyntaxKind.NumberKeyword,
                ),
              ]),
              _.createArrayLiteralExpression([], false),
            ),
          ],
          ts.NodeFlags.Const,
        ),
      ),
      _.createVariableStatement(
        undefined,
        _.createVariableDeclarationList(
          [
            _.createVariableDeclaration(
              _.createIdentifier('invalid'),
              undefined,
              _.createTypeReferenceNode(_.createIdentifier('ReadonlyArray'), [
                _.createKeywordTypeNode(
                  primitive === 'string'
                    ? ts.SyntaxKind.StringKeyword
                    : ts.SyntaxKind.NumberKeyword,
                ),
              ]),
              _.createArrayLiteralExpression([], false),
            ),
          ],
          ts.NodeFlags.Const,
        ),
      ),
      _.createExpressionStatement(
        _.createCallExpression(_.createIdentifier('describe'), undefined, [
          _.createStringLiteral(moduleName),
          _.createArrowFunction(
            undefined,
            undefined,
            [],
            undefined,
            _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
            _.createBlock(
              [
                _.createExpressionStatement(
                  _.createCallExpression(_.createIdentifier('describe'), undefined, [
                    _.createStringLiteral('Decoder'),
                    _.createArrowFunction(
                      undefined,
                      undefined,
                      [],
                      undefined,
                      _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                      _.createBlock(
                        [
                          _.createExpressionStatement(
                            _.createCallExpression(
                              _.createCallExpression(
                                _.createPropertyAccessExpression(
                                  _.createIdentifier('test'),
                                  _.createIdentifier('each'),
                                ),
                                undefined,
                                [
                                  _.createCallExpression(
                                    _.createIdentifier('cat'),
                                    undefined,
                                    [
                                      _.createCallExpression(
                                        _.createIdentifier('combineExpected'),
                                        undefined,
                                        [
                                          _.createIdentifier('valid'),
                                          _.createStringLiteral('Right'),
                                        ],
                                      ),
                                      _.createCallExpression(
                                        _.createIdentifier('combineExpected'),
                                        undefined,
                                        [
                                          _.createIdentifier('invalid'),
                                          _.createStringLiteral('Left'),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              undefined,
                              [
                                _.createStringLiteral(
                                  `validates valid ${primitive}s, and catches bad ${primitive}s`,
                                ),
                                _.createArrowFunction(
                                  undefined,
                                  undefined,
                                  [
                                    _.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      _.createIdentifier('str'),
                                      undefined,
                                      undefined,
                                      undefined,
                                    ),
                                    _.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      _.createIdentifier('expectedTag'),
                                      undefined,
                                      undefined,
                                      undefined,
                                    ),
                                  ],
                                  undefined,
                                  _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                                  _.createBlock(
                                    [
                                      _.createVariableStatement(
                                        undefined,
                                        _.createVariableDeclarationList(
                                          [
                                            _.createVariableDeclaration(
                                              _.createIdentifier('result'),
                                              undefined,
                                              undefined,
                                              _.createCallExpression(
                                                _.createPropertyAccessExpression(
                                                  _.createPropertyAccessExpression(
                                                    _.createIdentifier(moduleName),
                                                    _.createIdentifier('Decoder'),
                                                  ),
                                                  _.createIdentifier('decode'),
                                                ),
                                                undefined,
                                                [_.createIdentifier('str')],
                                              ),
                                            ),
                                          ],
                                          ts.NodeFlags.Const,
                                        ),
                                      ),
                                      _.createExpressionStatement(
                                        _.createCallExpression(
                                          _.createPropertyAccessExpression(
                                            _.createCallExpression(
                                              _.createIdentifier('expect'),
                                              undefined,
                                              [
                                                _.createPropertyAccessExpression(
                                                  _.createIdentifier('result'),
                                                  _.createIdentifier('_tag'),
                                                ),
                                              ],
                                            ),
                                            _.createIdentifier('toBe'),
                                          ),
                                          undefined,
                                          [_.createIdentifier('expectedTag')],
                                        ),
                                      ),
                                    ],
                                    true,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                        true,
                      ),
                    ),
                  ]),
                ),
                _.createExpressionStatement(
                  _.createCallExpression(_.createIdentifier('describe'), undefined, [
                    _.createStringLiteral('Encoder'),
                    _.createArrowFunction(
                      undefined,
                      undefined,
                      [],
                      undefined,
                      _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                      _.createBlock(
                        [
                          _.createExpressionStatement(
                            _.createCallExpression(
                              _.createCallExpression(
                                _.createPropertyAccessExpression(
                                  _.createIdentifier('test'),
                                  _.createIdentifier('each'),
                                ),
                                undefined,
                                [_.createIdentifier('valid')],
                              ),
                              undefined,
                              [
                                _.createStringLiteral(
                                  'encoding a decoded value yields original value',
                                ),
                                _.createArrowFunction(
                                  undefined,
                                  undefined,
                                  [
                                    _.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      _.createIdentifier('original'),
                                      undefined,
                                      undefined,
                                      undefined,
                                    ),
                                  ],
                                  undefined,
                                  _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                                  _.createBlock(
                                    [
                                      _.createVariableStatement(
                                        undefined,
                                        _.createVariableDeclarationList(
                                          [
                                            _.createVariableDeclaration(
                                              _.createIdentifier('roundtrip'),
                                              undefined,
                                              undefined,
                                              _.createCallExpression(
                                                _.createIdentifier('pipe'),
                                                undefined,
                                                [
                                                  _.createIdentifier('original'),
                                                  _.createPropertyAccessExpression(
                                                    _.createPropertyAccessExpression(
                                                      _.createIdentifier(moduleName),
                                                      _.createIdentifier('Decoder'),
                                                    ),
                                                    _.createIdentifier('decode'),
                                                  ),
                                                  _.createCallExpression(
                                                    _.createPropertyAccessExpression(
                                                      _.createIdentifier('E'),
                                                      _.createIdentifier('map'),
                                                    ),
                                                    undefined,
                                                    [
                                                      _.createPropertyAccessExpression(
                                                        _.createPropertyAccessExpression(
                                                          _.createIdentifier(moduleName),
                                                          _.createIdentifier('Encoder'),
                                                        ),
                                                        _.createIdentifier('encode'),
                                                      ),
                                                    ],
                                                  ),
                                                  _.createCallExpression(
                                                    _.createPropertyAccessExpression(
                                                      _.createIdentifier('E'),
                                                      _.createIdentifier('getOrElseW'),
                                                    ),
                                                    undefined,
                                                    [
                                                      _.createArrowFunction(
                                                        undefined,
                                                        undefined,
                                                        [],
                                                        undefined,
                                                        _.createToken(
                                                          ts.SyntaxKind
                                                            .EqualsGreaterThanToken,
                                                        ),
                                                        _.createStringLiteral(
                                                          'unexpected',
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ],
                                          ts.NodeFlags.Const,
                                        ),
                                      ),
                                      _.createExpressionStatement(
                                        _.createCallExpression(
                                          _.createPropertyAccessExpression(
                                            _.createCallExpression(
                                              _.createIdentifier('expect'),
                                              undefined,
                                              [_.createIdentifier('original')],
                                            ),
                                            _.createIdentifier('toEqual'),
                                          ),
                                          undefined,
                                          [_.createIdentifier('roundtrip')],
                                        ),
                                      ),
                                    ],
                                    true,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                        true,
                      ),
                    ),
                  ]),
                ),
                _.createExpressionStatement(
                  _.createCallExpression(_.createIdentifier('describe'), undefined, [
                    _.createStringLiteral('Eq'),
                    _.createArrowFunction(
                      undefined,
                      undefined,
                      [],
                      undefined,
                      _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                      _.createBlock(
                        [
                          _.createExpressionStatement(
                            _.createCallExpression(
                              _.createCallExpression(
                                _.createPropertyAccessExpression(
                                  _.createIdentifier('test'),
                                  _.createIdentifier('each'),
                                ),
                                undefined,
                                [
                                  _.createCallExpression(
                                    _.createPropertyAccessExpression(
                                      _.createIdentifier('RA'),
                                      _.createIdentifier('zipWith'),
                                    ),
                                    undefined,
                                    [
                                      _.createIdentifier('valid'),
                                      _.createIdentifier('valid'),
                                      _.createIdentifier('tuple'),
                                    ],
                                  ),
                                ],
                              ),
                              undefined,
                              [
                                _.createStringLiteral(
                                  `determines two ${primitive}s are equal`,
                                ),
                                _.createArrowFunction(
                                  undefined,
                                  undefined,
                                  [
                                    _.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      _.createIdentifier('str1'),
                                      undefined,
                                      undefined,
                                      undefined,
                                    ),
                                    _.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      _.createIdentifier('str2'),
                                      undefined,
                                      undefined,
                                      undefined,
                                    ),
                                  ],
                                  undefined,
                                  _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                                  _.createBlock(
                                    [
                                      _.createVariableStatement(
                                        undefined,
                                        _.createVariableDeclarationList(
                                          [
                                            _.createVariableDeclaration(
                                              _.createIdentifier('guard'),
                                              undefined,
                                              undefined,
                                              _.createPropertyAccessExpression(
                                                _.createPropertyAccessExpression(
                                                  _.createIdentifier(moduleName),
                                                  _.createIdentifier('Guard'),
                                                ),
                                                _.createIdentifier('is'),
                                              ),
                                            ),
                                          ],
                                          ts.NodeFlags.Const,
                                        ),
                                      ),
                                      _.createVariableStatement(
                                        undefined,
                                        _.createVariableDeclarationList(
                                          [
                                            _.createVariableDeclaration(
                                              _.createIdentifier('eq'),
                                              undefined,
                                              undefined,
                                              _.createPropertyAccessExpression(
                                                _.createPropertyAccessExpression(
                                                  _.createIdentifier(moduleName),
                                                  _.createIdentifier('Eq'),
                                                ),
                                                _.createIdentifier('equals'),
                                              ),
                                            ),
                                          ],
                                          ts.NodeFlags.Const,
                                        ),
                                      ),
                                      _.createIfStatement(
                                        _.createBinaryExpression(
                                          _.createPrefixUnaryExpression(
                                            ts.SyntaxKind.ExclamationToken,
                                            _.createCallExpression(
                                              _.createIdentifier('guard'),
                                              undefined,
                                              [_.createIdentifier('str1')],
                                            ),
                                          ),
                                          _.createToken(ts.SyntaxKind.BarBarToken),
                                          _.createPrefixUnaryExpression(
                                            ts.SyntaxKind.ExclamationToken,
                                            _.createCallExpression(
                                              _.createIdentifier('guard'),
                                              undefined,
                                              [_.createIdentifier('str2')],
                                            ),
                                          ),
                                        ),
                                        _.createBlock(
                                          [
                                            _.createThrowStatement(
                                              _.createNewExpression(
                                                _.createIdentifier('Error'),
                                                undefined,
                                                [
                                                  _.createStringLiteral(
                                                    'Unexpected result',
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ],
                                          true,
                                        ),
                                        undefined,
                                      ),
                                      _.createExpressionStatement(
                                        _.createCallExpression(
                                          _.createPropertyAccessExpression(
                                            _.createCallExpression(
                                              _.createIdentifier('expect'),
                                              undefined,
                                              [
                                                _.createCallExpression(
                                                  _.createIdentifier('eq'),
                                                  undefined,
                                                  [
                                                    _.createIdentifier('str1'),
                                                    _.createIdentifier('str2'),
                                                  ],
                                                ),
                                              ],
                                            ),
                                            _.createIdentifier('toBe'),
                                          ),
                                          undefined,
                                          [_.createTrue()],
                                        ),
                                      ),
                                    ],
                                    true,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                        true,
                      ),
                    ),
                  ]),
                ),
                _.createExpressionStatement(
                  _.createCallExpression(_.createIdentifier('describe'), undefined, [
                    _.createStringLiteral('Guard'),
                    _.createArrowFunction(
                      undefined,
                      undefined,
                      [],
                      undefined,
                      _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                      _.createBlock(
                        [
                          _.createExpressionStatement(
                            _.createCallExpression(
                              _.createCallExpression(
                                _.createPropertyAccessExpression(
                                  _.createIdentifier('test'),
                                  _.createIdentifier('each'),
                                ),
                                undefined,
                                [
                                  _.createCallExpression(
                                    _.createIdentifier('cat'),
                                    undefined,
                                    [
                                      _.createCallExpression(
                                        _.createIdentifier('combineExpected'),
                                        undefined,
                                        [_.createIdentifier('valid'), _.createTrue()],
                                      ),
                                      _.createCallExpression(
                                        _.createIdentifier('combineExpected'),
                                        undefined,
                                        [_.createIdentifier('invalid'), _.createFalse()],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              undefined,
                              [
                                _.createStringLiteral(
                                  `validates valid ${primitive}s, and catches bad ${primitive}s`,
                                ),
                                _.createArrowFunction(
                                  undefined,
                                  undefined,
                                  [
                                    _.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      _.createIdentifier('str'),
                                      undefined,
                                      undefined,
                                      undefined,
                                    ),
                                    _.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      _.createIdentifier('expectedTag'),
                                      undefined,
                                      undefined,
                                      undefined,
                                    ),
                                  ],
                                  undefined,
                                  _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                                  _.createBlock(
                                    [
                                      _.createVariableStatement(
                                        undefined,
                                        _.createVariableDeclarationList(
                                          [
                                            _.createVariableDeclaration(
                                              _.createIdentifier('result'),
                                              undefined,
                                              undefined,
                                              _.createCallExpression(
                                                _.createPropertyAccessExpression(
                                                  _.createPropertyAccessExpression(
                                                    _.createIdentifier(moduleName),
                                                    _.createIdentifier('Guard'),
                                                  ),
                                                  _.createIdentifier('is'),
                                                ),
                                                undefined,
                                                [_.createIdentifier('str')],
                                              ),
                                            ),
                                          ],
                                          ts.NodeFlags.Const,
                                        ),
                                      ),
                                      _.createExpressionStatement(
                                        _.createCallExpression(
                                          _.createPropertyAccessExpression(
                                            _.createCallExpression(
                                              _.createIdentifier('expect'),
                                              undefined,
                                              [_.createIdentifier('result')],
                                            ),
                                            _.createIdentifier('toBe'),
                                          ),
                                          undefined,
                                          [_.createIdentifier('expectedTag')],
                                        ),
                                      ),
                                    ],
                                    true,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                        true,
                      ),
                    ),
                  ]),
                ),
                _.createExpressionStatement(
                  _.createCallExpression(_.createIdentifier('describe'), undefined, [
                    _.createStringLiteral('TaskDecoder'),
                    _.createArrowFunction(
                      undefined,
                      undefined,
                      [],
                      undefined,
                      _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                      _.createBlock(
                        [
                          _.createExpressionStatement(
                            _.createCallExpression(
                              _.createCallExpression(
                                _.createPropertyAccessExpression(
                                  _.createIdentifier('test'),
                                  _.createIdentifier('each'),
                                ),
                                undefined,
                                [
                                  _.createCallExpression(
                                    _.createIdentifier('cat'),
                                    undefined,
                                    [
                                      _.createCallExpression(
                                        _.createIdentifier('combineExpected'),
                                        undefined,
                                        [
                                          _.createIdentifier('valid'),
                                          _.createStringLiteral('Right'),
                                        ],
                                      ),
                                      _.createCallExpression(
                                        _.createIdentifier('combineExpected'),
                                        undefined,
                                        [
                                          _.createIdentifier('invalid'),
                                          _.createStringLiteral('Left'),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              undefined,
                              [
                                _.createStringLiteral(
                                  `validates valid ${primitive}, and catches bad ${primitive}`,
                                ),
                                _.createArrowFunction(
                                  [_.createModifier(ts.SyntaxKind.AsyncKeyword)],
                                  undefined,
                                  [
                                    _.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      _.createIdentifier('str'),
                                      undefined,
                                      undefined,
                                      undefined,
                                    ),
                                    _.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      _.createIdentifier('expectedTag'),
                                      undefined,
                                      undefined,
                                      undefined,
                                    ),
                                  ],
                                  undefined,
                                  _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                                  _.createBlock(
                                    [
                                      _.createVariableStatement(
                                        undefined,
                                        _.createVariableDeclarationList(
                                          [
                                            _.createVariableDeclaration(
                                              _.createIdentifier('result'),
                                              undefined,
                                              undefined,
                                              _.createAwaitExpression(
                                                _.createCallExpression(
                                                  _.createCallExpression(
                                                    _.createPropertyAccessExpression(
                                                      _.createPropertyAccessExpression(
                                                        _.createIdentifier(moduleName),
                                                        _.createIdentifier('TaskDecoder'),
                                                      ),
                                                      _.createIdentifier('decode'),
                                                    ),
                                                    undefined,
                                                    [_.createIdentifier('str')],
                                                  ),
                                                  undefined,
                                                  [],
                                                ),
                                              ),
                                            ),
                                          ],
                                          ts.NodeFlags.Const |
                                            ts.NodeFlags.AwaitContext |
                                            ts.NodeFlags.ContextFlags |
                                            ts.NodeFlags.TypeExcludesFlags,
                                        ),
                                      ),
                                      _.createExpressionStatement(
                                        _.createCallExpression(
                                          _.createPropertyAccessExpression(
                                            _.createCallExpression(
                                              _.createIdentifier('expect'),
                                              undefined,
                                              [
                                                _.createPropertyAccessExpression(
                                                  _.createIdentifier('result'),
                                                  _.createIdentifier('_tag'),
                                                ),
                                              ],
                                            ),
                                            _.createIdentifier('toBe'),
                                          ),
                                          undefined,
                                          [_.createIdentifier('expectedTag')],
                                        ),
                                      ),
                                    ],
                                    true,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                        true,
                      ),
                    ),
                  ]),
                ),
                _.createExpressionStatement(
                  _.createCallExpression(_.createIdentifier('describe'), undefined, [
                    _.createStringLiteral('Type'),
                    _.createArrowFunction(
                      undefined,
                      undefined,
                      [],
                      undefined,
                      _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                      _.createBlock(
                        [
                          _.createExpressionStatement(
                            _.createCallExpression(
                              _.createCallExpression(
                                _.createPropertyAccessExpression(
                                  _.createIdentifier('test'),
                                  _.createIdentifier('each'),
                                ),
                                undefined,
                                [
                                  _.createCallExpression(
                                    _.createIdentifier('cat'),
                                    undefined,
                                    [
                                      _.createCallExpression(
                                        _.createIdentifier('combineExpected'),
                                        undefined,
                                        [
                                          _.createIdentifier('valid'),
                                          _.createStringLiteral('Right'),
                                        ],
                                      ),
                                      _.createCallExpression(
                                        _.createIdentifier('combineExpected'),
                                        undefined,
                                        [
                                          _.createIdentifier('invalid'),
                                          _.createStringLiteral('Left'),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              undefined,
                              [
                                _.createStringLiteral(
                                  'validates valid strings, and catches bad strings',
                                ),
                                _.createArrowFunction(
                                  undefined,
                                  undefined,
                                  [
                                    _.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      _.createIdentifier('str'),
                                      undefined,
                                      undefined,
                                      undefined,
                                    ),
                                    _.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      _.createIdentifier('expectedTag'),
                                      undefined,
                                      undefined,
                                      undefined,
                                    ),
                                  ],
                                  undefined,
                                  _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                                  _.createBlock(
                                    [
                                      _.createVariableStatement(
                                        undefined,
                                        _.createVariableDeclarationList(
                                          [
                                            _.createVariableDeclaration(
                                              _.createIdentifier('result'),
                                              undefined,
                                              undefined,
                                              _.createCallExpression(
                                                _.createPropertyAccessExpression(
                                                  _.createPropertyAccessExpression(
                                                    _.createIdentifier(moduleName),
                                                    _.createIdentifier('Type'),
                                                  ),
                                                  _.createIdentifier('decode'),
                                                ),
                                                undefined,
                                                [_.createIdentifier('str')],
                                              ),
                                            ),
                                          ],
                                          ts.NodeFlags.Const,
                                        ),
                                      ),
                                      _.createExpressionStatement(
                                        _.createCallExpression(
                                          _.createPropertyAccessExpression(
                                            _.createCallExpression(
                                              _.createIdentifier('expect'),
                                              undefined,
                                              [
                                                _.createPropertyAccessExpression(
                                                  _.createIdentifier('result'),
                                                  _.createIdentifier('_tag'),
                                                ),
                                              ],
                                            ),
                                            _.createIdentifier('toBe'),
                                          ),
                                          undefined,
                                          [_.createIdentifier('expectedTag')],
                                        ),
                                      ),
                                    ],
                                    true,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                        true,
                      ),
                    ),
                  ]),
                ),
                _.createExpressionStatement(
                  _.createCallExpression(_.createIdentifier('describe'), undefined, [
                    _.createStringLiteral('Arbitrary'),
                    _.createArrowFunction(
                      undefined,
                      undefined,
                      [],
                      undefined,
                      _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                      _.createBlock(
                        [
                          _.createExpressionStatement(
                            _.createCallExpression(_.createIdentifier('it'), undefined, [
                              _.createStringLiteral(`generates valid ${moduleName}`),
                              _.createArrowFunction(
                                undefined,
                                undefined,
                                [],
                                undefined,
                                _.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                                _.createBlock(
                                  [
                                    _.createExpressionStatement(
                                      _.createCallExpression(
                                        _.createIdentifier('validateArbitrary'),
                                        undefined,
                                        [
                                          _.createIdentifier(moduleName),
                                          _.createPropertyAccessExpression(
                                            _.createIdentifier(moduleName),
                                            _.createIdentifier(`is${moduleName}`),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                  true,
                                ),
                              ),
                            ]),
                          ),
                        ],
                        true,
                      ),
                    ),
                  ]),
                ),
              ],
              true,
            ),
          ),
        ]),
      ),
    ],
    _.createNodeArray,
    nodes => printer.printList(ts.ListFormat.MultiLine, nodes, sourceFile),
    Str.replace(/const valid/gm, '\nconst valid'),
    Str.replace(/const invalid/gm, '\nconst invalid'),
    Str.replace(/describe/gm, '\ndescribe'),
  )
}
