/**
 * SchemableExt instances for Arbitrary
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 0.0.3
 */
import * as Arb from './internal/ArbitraryBase'
import { SchemableExt1 } from './SchemableExt'

/** Generic */
import * as mapFromEntries from './generic/mapFromEntries'
import * as optionFromExclude from './generic/optionFromExclude'
import * as optionFromNullable from './generic/optionFromNullable'
import * as optionFromUndefined from './generic/optionFromUndefined'

/** Number */
import * as int from './number/int'
import * as natural from './number/natural'
import * as negativeFloat from './number/negativeFloat'
import * as negativeInt from './number/negativeInt'
import * as nonNegativeFloat from './number/nonNegativeFloat'
import * as nonPositiveFloat from './number/nonPositiveFloat'
import * as nonPositiveInt from './number/nonPositiveInt'
import * as positiveFloat from './number/positiveFloat'
import * as positiveInt from './number/positiveInt'

/** String */
import * as ascii from './string/ascii'
import * as base64 from './string/base64'
import * as base64Url from './string/base64Url'
import * as bigIntString from './string/bigIntString'
import * as btcAddress from './string/btcAddress'
import * as creditCard from './string/creditCard'
import * as emailAddress from './string/emailAddress'
import * as hexColor from './string/hexColor'
import * as hexadecimal from './string/hexadecimal'
import * as hslColor from './string/hslColor'
import * as intString from './string/intString'
import * as isoDateString from './string/isoDateString'
import * as jwt from './string/jwt'
import * as naturalString from './string/naturalString'
import * as negativeFloatString from './string/negativeFloatString'
import * as negativeIntString from './string/negativeIntString'
import * as nonNegativeFloatString from './string/nonNegativeFloatString'
import * as nonPositiveFloatString from './string/nonPositiveFloatString'
import * as nonPositiveIntString from './string/nonPositiveIntString'
import * as nonemptyString from './string/nonemptyString'
import * as positiveFloatString from './string/positiveFloatString'
import * as positiveIntString from './string/positiveIntString'
import * as rgb from './string/rgb'
import * as uuid from './string/uuid'

/** Date */
import * as safeDate from './date/safeDate'

/**
 * @since 0.0.1
 * @category Instances
 */
export const Schemable: SchemableExt1<Arb.URI> = {
  ...Arb.Schemable,
  ...Arb.WithBrand,
  ...Arb.WithPattern,
  ...Arb.WithRefine,
  ...Arb.WithUnknownContainers,
  mapFromEntries: mapFromEntries.Arbitrary,
  optionFromExclude: optionFromExclude.Arbitrary,
  optionFromNullable: optionFromNullable.Arbitrary,
  optionFromUndefined: optionFromUndefined.Arbitrary,
  int: int.Arbitrary,
  natural: natural.Arbitrary,
  negativeFloat: negativeFloat.Arbitrary,
  negativeInt: negativeInt.Arbitrary,
  nonNegativeFloat: nonNegativeFloat.Arbitrary,
  nonPositiveFloat: nonPositiveFloat.Arbitrary,
  nonPositiveInt: nonPositiveInt.Arbitrary,
  positiveFloat: positiveFloat.Arbitrary,
  positiveInt: positiveInt.Arbitrary,
  ascii: ascii.Arbitrary,
  base64: base64.Arbitrary,
  base64Url: base64Url.Arbitrary,
  bigIntString: bigIntString.Arbitrary,
  btcAddress: btcAddress.Arbitrary,
  creditCard: creditCard.Arbitrary,
  emailAddress: emailAddress.Arbitrary,
  hexColor: hexColor.Arbitrary,
  hexadecimal: hexadecimal.Arbitrary,
  hslColor: hslColor.Arbitrary,
  intString: intString.Arbitrary,
  isoDateString: isoDateString.Arbitrary,
  jwt: jwt.Arbitrary,
  naturalString: naturalString.Arbitrary,
  negativeFloatString: negativeFloatString.Arbitrary,
  negativeIntString: negativeIntString.Arbitrary,
  nonNegativeFloatString: nonNegativeFloatString.Arbitrary,
  nonPositiveFloatString: nonPositiveFloatString.Arbitrary,
  nonPositiveIntString: nonPositiveIntString.Arbitrary,
  nonemptyString: nonemptyString.Arbitrary,
  positiveFloatString: positiveFloatString.Arbitrary,
  positiveIntString: positiveIntString.Arbitrary,
  rgb: rgb.Arbitrary,
  uuid: uuid.Arbitrary,
  safeDate: safeDate.Arbitrary,
}
