/**
 * SchemableExt instances for Arbitrary
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 0.0.3
 */
import * as Arb from './internal/ArbitraryBase'
import { SchemableExt1 } from './SchemableExt'

/** Number */
import * as Int from './number/Int'
import * as Natural from './number/Natural'
import * as NegativeFloat from './number/NegativeFloat'
import * as NegativeInt from './number/NegativeInt'
import * as NonNegativeFloat from './number/NonNegativeFloat'
import * as PositiveFloat from './number/PositiveFloat'
import * as PositiveInt from './number/PositiveInt'

/** String */
import * as ASCII from './string/ASCII'
import * as Base64 from './string/Base64'
import * as Base64Url from './string/Base64Url'
import * as BtcAddress from './string/BtcAddress'
import * as CreditCard from './string/CreditCard'
import * as EmailAddress from './string/EmailAddress'
import * as HexColor from './string/HexColor'
import * as Hexadecimal from './string/Hexadecimal'
import * as ISODateString from './string/ISODateString'
import * as IntString from './string/IntString'
import * as JWT from './string/JWT'
import * as NaturalString from './string/NaturalString'
import * as NegativeFloatString from './string/NegativeFloatString'
import * as NegativeIntString from './string/NegativeIntString'
import * as NonNegativeFloatString from './string/NonNegativeFloatString'
import * as NonemptyString from './string/NonemptyString'
import * as PositiveFloatString from './string/PositiveFloatString'
import * as PositiveIntString from './string/PositiveIntString'
import * as UUID from './string/UUID'

/** Date */
import * as SafeDate from './date/SafeDate'

/**
 * @since 0.0.1
 * @category Instances
 */
export const Schemable: SchemableExt1<Arb.URI> = {
  ...Arb.Schemable,
  Int: Int.Arbitrary,
  Natural: Natural.Arbitrary,
  NegativeFloat: NegativeFloat.Arbitrary,
  NegativeInt: NegativeInt.Arbitrary,
  NonNegativeFloat: NonNegativeFloat.Arbitrary,
  PositiveFloat: PositiveFloat.Arbitrary,
  PositiveInt: PositiveInt.Arbitrary,
  ASCII: ASCII.Arbitrary,
  Base64: Base64.Arbitrary,
  Base64Url: Base64Url.Arbitrary,
  BtcAddress: BtcAddress.Arbitrary,
  CreditCard: CreditCard.Arbitrary,
  EmailAddress: EmailAddress.Arbitrary,
  HexColor: HexColor.Arbitrary,
  Hexadecimal: Hexadecimal.Arbitrary,
  ISODateString: ISODateString.Arbitrary,
  IntString: IntString.Arbitrary,
  JWT: JWT.Arbitrary,
  NaturalString: NaturalString.Arbitrary,
  NegativeFloatString: NegativeFloatString.Arbitrary,
  NegativeIntString: NegativeIntString.Arbitrary,
  NonNegativeFloatString: NonNegativeFloatString.Arbitrary,
  NonemptyString: NonemptyString.Arbitrary,
  PositiveFloatString: PositiveFloatString.Arbitrary,
  PositiveIntString: PositiveIntString.Arbitrary,
  UUID: UUID.Arbitrary,
  SafeDate: SafeDate.Arbitrary,
}
