/**
 * SchemableExt intstances for Decoder
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 0.0.1
 */
import * as D from 'io-ts/Decoder'
import { SchemableExt2C } from './SchemableExt'

/** Number */
import * as Int from './number/Int'
import * as NegativeInt from './number/NegativeInt'
import * as PositiveInt from './number/PositiveInt'

/** String */
import * as ISODateString from './string/ISODateString'
import * as UUID from './string/UUID'

/** Date */
import * as SafeDate from './date/SafeDate'

/**
 * @since 0.0.1
 * @category Instances
 */
export const Schemable: SchemableExt2C<D.URI> = {
  ...D.Schemable,
  Int: Int.Decoder,
  NegativeInt: NegativeInt.Decoder,
  PositiveInt: PositiveInt.Decoder,
  ISODateString: ISODateString.Decoder,
  UUID: UUID.Decoder,
  SafeDate: SafeDate.Decoder,
}
