/**
 * SchemableExt intstances for Eq
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 0.0.1
 */
import * as Eq from 'io-ts/Eq'
import { SchemableExt1 } from './SchemableExt'

/** Number */
import * as Int from './number/Int'
import * as NegativeInt from './number/NegativeInt'
import * as PositiveInt from './number/PositiveInt'

/** String */
import * as ISODateString from './string/ISODateString'
import * as IntString from './string/IntString'
import * as NegativeIntString from './string/NegativeIntString'
import * as PositiveIntString from './string/PositiveIntString'
import * as UUID from './string/UUID'

/** Date */
import * as SafeDate from './date/SafeDate'

/**
 * @since 0.0.1
 * @category Instances
 */
export const Schemable: SchemableExt1<Eq.URI> = {
  ...Eq.Schemable,
  Int: Int.Eq,
  NegativeInt: NegativeInt.Eq,
  PositiveInt: PositiveInt.Eq,
  ISODateString: ISODateString.Eq,
  IntString: IntString.Eq,
  NegativeIntString: NegativeIntString.Eq,
  PositiveIntString: PositiveIntString.Eq,
  UUID: UUID.Eq,
  SafeDate: SafeDate.Eq,
}
