/**
 * SchemableExt instances for Guard
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 0.0.1
 */
import * as G from './internal/GuardBase'
import { SchemableExt1 } from './SchemableExt'

/** Schemables */
import * as WithBrand from './schemables/WithBrand'
import * as WithCheckDigit from './schemables/WithCheckDigit'
import * as WithInvariant from './schemables/WithInvariant'
import * as WithPadding from './schemables/WithPadding'
import * as WithPattern from './schemables/WithPattern'
import * as WithRefine from './schemables/WithRefine'
import * as WithUnknownContainers from './schemables/WithUnknownContainers'

/** Generic */
import * as mapFromEntries from './generic/mapFromEntries'
import * as optionFromExclude from './generic/optionFromExclude'
import * as optionFromNullable from './generic/optionFromNullable'
import * as optionFromUndefined from './generic/optionFromUndefined'

/** Number */
import * as bigIntFromString from './number/bigIntFromString'
import * as float from './number/float'
import * as floatFromString from './number/floatFromString'
import * as int from './number/int'
import * as intFromString from './number/intFromString'

/** Date */
import * as date from './date/date'
import * as dateFromIsoString from './date/dateFromIsoString'

/**
 * @since 0.0.1
 * @category Instances
 */
export const Schemable: SchemableExt1<G.URI> = {
  ...G.Schemable,
  ...WithBrand.Guard,
  ...WithCheckDigit.Guard,
  ...WithInvariant.Guard,
  ...WithPadding.Guard,
  ...WithPattern.Guard,
  ...WithRefine.Guard,
  ...WithUnknownContainers.Guard,
  mapFromEntries: mapFromEntries.Guard,
  optionFromExclude: optionFromExclude.Guard,
  optionFromNullable: optionFromNullable.Guard,
  optionFromUndefined: optionFromUndefined.Guard,
  bigIntFromString: bigIntFromString.Guard,
  float: float.Guard,
  floatFromString: floatFromString.Guard,
  int: int.Guard,
  intFromString: intFromString.Guard,
  date: date.Guard,
  dateFromIsoString: dateFromIsoString.Guard,
}
