/**
 * SchemableExt instances for JsonSchema
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 1.2.0
 */
import * as JS from './base/JsonSchemaBase'
import { SchemableExt2 } from './SchemableExt'
import * as WithAnnotate from './schemables/WithAnnotate/instances/json-schema'
import * as WithBrand from './schemables/WithBrand/instances/json-schema'
import * as WithCheckDigit from './schemables/WithCheckDigit/instances/json-schema'
import * as WithDate from './schemables/WithDate/instances/json-schema'
import * as WithFloat from './schemables/WithFloat/instances/json-schema'
import * as WithInt from './schemables/WithInt/instances/json-schema'
import * as WithInvariant from './schemables/WithInvariant/instances/json-schema'
import * as WithJson from './schemables/WithJson/instances/json-schema'
import * as WithMap from './schemables/WithMap/instances/json-schema'
import * as WithOption from './schemables/WithOption/instances/json-schema'
import * as WithOptional from './schemables/WithOptional/instances/json-schema'
import * as WithPadding from './schemables/WithPadding/instances/json-schema'
import * as WithPattern from './schemables/WithPattern/instances/json-schema'
import * as WithRefine from './schemables/WithRefine/instances/json-schema'
import * as WithUnknownContainers from './schemables/WithUnknownContainers/instances/json-schema'
import { interpret } from './SchemaExt'
export type {
  /**
   * @since 1.2.0
   * @category Model
   */
  JsonSchema,
} from './base/JsonSchemaBase'

/**
 * @since 1.2.0
 * @category Instances
 */
export const Schemable: SchemableExt2<JS.URI> = {
  ...JS.Schemable,
  ...WithAnnotate.JsonSchema,
  ...WithBrand.JsonSchema,
  ...WithCheckDigit.JsonSchema,
  ...WithDate.JsonSchema,
  ...WithFloat.JsonSchema,
  ...WithInt.JsonSchema,
  ...WithInvariant.JsonSchema,
  ...WithJson.JsonSchema,
  ...WithMap.JsonSchema,
  ...WithOption.JsonSchema,
  ...WithOptional.JsonSchema,
  ...WithPadding.JsonSchema,
  ...WithPattern.JsonSchema,
  ...WithRefine.JsonSchema,
  ...WithUnknownContainers.JsonSchema,
}

/**
 * @since 1.2.0
 * @category Interpreters
 */
export const getJsonSchema = interpret(Schemable)
