/**
 * SchemableExt instances for Printer
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 1.1.0
 */
import * as P from './base/PrinterBase'
import { SchemableExt2 } from './SchemableExt'
import * as WithAnnotate from './schemables/WithAnnotate/instances/printer'
import * as WithBrand from './schemables/WithBrand/instances/printer'
import * as WithCheckDigit from './schemables/WithCheckDigit/instances/printer'
import * as WithDate from './schemables/WithDate/instances/printer'
import * as WithFloat from './schemables/WithFloat/instances/printer'
import * as WithInt from './schemables/WithInt/instances/printer'
import * as WithInvariant from './schemables/WithInvariant/instances/printer'
import * as WithJson from './schemables/WithJson/instances/printer'
import * as WithMap from './schemables/WithMap/instances/printer'
import * as WithOption from './schemables/WithOption/instances/printer'
import * as WithOptional from './schemables/WithOptional/instances/printer'
import * as WithPadding from './schemables/WithPadding/instances/printer'
import * as WithPattern from './schemables/WithPattern/instances/printer'
import * as WithRefine from './schemables/WithRefine/instances/printer'
import * as WithUnknownContainers from './schemables/WithUnknownContainers/instances/printer'
import { interpret } from './SchemaExt'
export type {
  /**
   * @since 1.1.0
   * @category Model
   */
  Printer,
} from './base/PrinterBase'

/**
 * @since 1.1.0
 * @category Instances
 */
export const Schemable: SchemableExt2<P.URI> = {
  ...P.Schemable,
  ...WithAnnotate.Printer,
  ...WithBrand.Printer,
  ...WithCheckDigit.Printer,
  ...WithDate.Printer,
  ...WithFloat.Printer,
  ...WithInt.Printer,
  ...WithInvariant.Printer,
  ...WithJson.Printer,
  ...WithMap.Printer,
  ...WithOption.Printer,
  ...WithOptional.Printer,
  ...WithPadding.Printer,
  ...WithPattern.Printer,
  ...WithRefine.Printer,
  ...WithUnknownContainers.Printer,
}

/**
 * @since 1.1.0
 * @category Interpreters
 */
export const getPrinter = interpret(Schemable)
