/**
 * The extended Schemable typeclass
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 1.0.0
 */
import { SchemableLambda } from 'schemata-ts/HKT'
import { WithAnnotate } from 'schemata-ts/schemables/WithAnnotate/definition'
import { WithCheckDigit } from 'schemata-ts/schemables/WithCheckDigit/definition'
import { WithDate } from 'schemata-ts/schemables/WithDate/definition'
import { WithInvariant } from 'schemata-ts/schemables/WithInvariant/definition'
import { WithJson } from 'schemata-ts/schemables/WithJson/definition'
import { WithMap } from 'schemata-ts/schemables/WithMap/definition'
import { WithOption } from 'schemata-ts/schemables/WithOption/definition'
import { WithOptional } from 'schemata-ts/schemables/WithOptional/definition'
import { WithPadding } from 'schemata-ts/schemables/WithPadding/definition'
import { WithPattern } from 'schemata-ts/schemables/WithPattern/definition'
import { WithPrimitives } from 'schemata-ts/schemables/WithPrimitives/definition'
import { WithRefine } from 'schemata-ts/schemables/WithRefine/definition'
import { WithStructM } from 'schemata-ts/schemables/WithStructM/definition'

/**
 * @since 2.0.0
 * @category Instances
 */
export interface Schemable<S extends SchemableLambda>
  extends WithAnnotate<S>,
    WithCheckDigit<S>,
    WithDate<S>,
    WithInvariant<S>,
    WithJson<S>,
    WithMap<S>,
    WithOption<S>,
    WithOptional<S>,
    WithPadding<S>,
    WithPattern<S>,
    WithPrimitives<S>,
    WithRefine<S>,
    WithStructM<S> {}
