/**
 * SchemableExt intstances for TaskDecoder
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 0.0.1
 */
import * as TD from 'io-ts/TaskDecoder'
import { SchemableExt2C } from './SchemableExt'

/** Number */
import * as Int from './number/Int'
import * as NegativeInt from './number/NegativeInt'
import * as PositiveInt from './number/PositiveInt'

/** String */
import * as ISODateString from './string/ISODateString'
import * as UUID from './string/UUID'

/** Date */
import * as SafeDate from './date/SafeDate'

/**
 * @since 0.0.1
 * @category Instances
 */
export const Schemable: SchemableExt2C<TD.URI> = {
  ...TD.Schemable,
  Int: Int.TaskDecoder,
  NegativeInt: NegativeInt.TaskDecoder,
  PositiveInt: PositiveInt.TaskDecoder,
  ISODateString: ISODateString.TaskDecoder,
  UUID: UUID.TaskDecoder,
  SafeDate: SafeDate.TaskDecoder,
}
