/**
 * SchemableExt instances for Type
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 0.0.1
 */
import * as t from 'io-ts/Type'
import { SchemableExt1 } from './SchemableExt'

/** Number */
import * as Int from './number/Int'
import * as Natural from './number/Natural'
import * as NegativeInt from './number/NegativeInt'
import * as PositiveInt from './number/PositiveInt'

/** String */
import * as EmailAddress from './string/EmailAddress'
import * as ISODateString from './string/ISODateString'
import * as IntString from './string/IntString'
import * as NaturalString from './string/NaturalString'
import * as NegativeIntString from './string/NegativeIntString'
import * as NonemptyString from './string/NonemptyString'
import * as PositiveIntString from './string/PositiveIntString'
import * as UUID from './string/UUID'

/** Date */
import * as SafeDate from './date/SafeDate'

/**
 * @since 0.0.1
 * @category Instances
 */
export const Schemable: SchemableExt1<t.URI> = {
  ...t.Schemable,
  Int: Int.Type,
  Natural: Natural.Type,
  NegativeInt: NegativeInt.Type,
  PositiveInt: PositiveInt.Type,
  EmailAddress: EmailAddress.Type,
  ISODateString: ISODateString.Type,
  IntString: IntString.Type,
  NaturalString: NaturalString.Type,
  NegativeIntString: NegativeIntString.Type,
  NonemptyString: NonemptyString.Type,
  PositiveIntString: PositiveIntString.Type,
  UUID: UUID.Type,
  SafeDate: SafeDate.Type,
}
