/**
 * SchemableExt instances for Type
 *
 * **Warning: DO NOT EDIT, this module is autogenerated**
 *
 * @since 0.0.1
 */
import * as t from './internal/TypeBase'
import { SchemableExt1 } from './SchemableExt'

/** Schemables */
import * as WithBrand from './schemables/WithBrand'
import * as WithCheckDigit from './schemables/WithCheckDigit'
import * as WithFloat from './schemables/WithFloat'
import * as WithInt from './schemables/WithInt'
import * as WithInvariant from './schemables/WithInvariant'
import * as WithPadding from './schemables/WithPadding'
import * as WithPattern from './schemables/WithPattern'
import * as WithRefine from './schemables/WithRefine'
import * as WithUnknownContainers from './schemables/WithUnknownContainers'

/** Generic */
import * as mapFromEntries from './generic/mapFromEntries'
import * as optionFromExclude from './generic/optionFromExclude'
import * as optionFromNullable from './generic/optionFromNullable'
import * as optionFromUndefined from './generic/optionFromUndefined'

/** Date */
import * as date from './date/date'
import * as dateFromIsoString from './date/dateFromIsoString'

/**
 * @since 0.0.1
 * @category Instances
 */
export const Schemable: SchemableExt1<t.URI> = {
  ...t.Schemable,
  ...WithBrand.Type,
  ...WithCheckDigit.Type,
  ...WithFloat.Type,
  ...WithInt.Type,
  ...WithInvariant.Type,
  ...WithPadding.Type,
  ...WithPattern.Type,
  ...WithRefine.Type,
  ...WithUnknownContainers.Type,
  mapFromEntries: mapFromEntries.Type,
  optionFromExclude: optionFromExclude.Type,
  optionFromNullable: optionFromNullable.Type,
  optionFromUndefined: optionFromUndefined.Type,
  date: date.Type,
  dateFromIsoString: dateFromIsoString.Type,
}
